version: '3'

tasks:
  gofmt:
    desc: Format Go source files
    aliases: [fmt]
    cmds:
      - gofmt -s -w .

  build:
    desc: Build the lxm binary
    deps:
      - gofmt
    cmds:
      - go build -v -o ./bin/lxm ./cmd/lxm

  test:
    desc: Run all project tests with race detector
    cmds:
      - go test -v -race ./...

  lint:
    desc: Run golangci-lint
    deps:
      - gofmt
    cmds:
      - golangci-lint run ./...

  clean:
    desc: Remove the compiled binary
    cmds:
      - rm -f ./bin/lxm

  run:
    desc: Run the application directly
    cmds:
      - go run -v ./cmd/lxm {{.CLI_ARGS}}

  install:
    desc: Install the binary to the GOBIN directory
    cmds:
      - go install -v ./cmd/lxm
